modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/BasiqueEvangelist/RichLocalTextLib/issues"
license = "LGPL-3.0-only"
logoFile = "icon.png"

[[mods]]
modId = "richlocaltextlib"
version = "${version}"
displayName = "RichLocalTextLib"
authors = "BasiqueEvangelist, Jetsparrow"
description = '''
Rich text support for translations
'''

[[dependencies.richlocaltextlib]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.richlocaltextlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"